import { Geist, Geist_Mono, Alex_Brush, Alegreya_SC, Aleo } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const alexBrush = Alex_Brush({
  variable: "--font-alex-brush", // Define a CSS variable for Alex Brush
  subsets: ["latin"],
  weight: "400", // Alex Brush typically uses a regular weight
});

const alegreyaSC = Alegreya_SC({
  subsets: ['latin'], // Specify subsets
  variable: '--font-alegreya-sc', // Create a CSS variable for the font
  weight: ['400', '500', '700'], // Specify font weights you need
});

const aleo = Aleo({
  subsets: ['latin'], // Specify the subset
  weight: ['300', '400', '700'], // Include font weights you need
  variable: '--font-aleo', // Create a CSS variable for the font
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${alexBrush.variable} ${alegreyaSC.variable} ${aleo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
