
name: LyaimTech backend

on: 
    push: 
        branches: [ main ]

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            
            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v5 
              with:
                context: ./backend
                file: ./backend/Dockerfile
                push: true
                tags: |
                  rohitsamasi555/lyaim-tech-backend:${{ github.sha }} 
                  rohitsamasi555/lyaim-tech-backend:latest
            
            - name: Deploy to VM
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: "3.89.35.211" 
                username: "ubuntu" 
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                  sudo docker pull rohitsamasi555/lyaim-tech-backend:latest
                  sudo docker stop lyaim-backend || true
                  sudo docker rm lyaim-backend || true
                  sudo docker run -d \
                    --name lyaim-backend \
                    -e PORT=9000 \
                    -e JWT_SECRET="${JWT_SECRET}" \
                    -e NODE_ENV=development \
                    -e PAYPAL_MODE="${PAYPAL_MODE}" \
                    -e PAYPAL_CLIENT_ID="${PAYPAL_CLIENT_ID}" \
                    -e PAYPAL_CLIENT_SECRET="${PAYPAL_CLIENT_SECRET}" \
                    -e MONGO_URL="${MONGO_URL}" \
                    -p 9000:9000 \
                    --restart always \
                    rohitsamsi555/lyaim-tech-backend:latest
                  sudo docker rmi $(docker images -aq)
              env:
                JWT_SECRET: ${{ secrets.JWT_SECRET }}
                PAYPAL_MODE: ${{ secrets.PAYPAL_MODE }}
                PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
                PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
                MONGO_URL: ${{ secrets.MONGO_URL }}
