name: LyaimTech frontend

on: 
    push: 
        branches: [ main ]

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                tags: | 
                  narsibhati6545/lyaim-tech-frontend:${{ github.sha }} 
                  narsibhati6545/lyaim-tech-frontend:latest

            - name: Deploy to VM
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: "98.81.206.98"
                username: "ubuntu" # Your SSH user
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                  sudo docker pull narsibhati6545/lyaim-tech-frontend:latest
                  sudo docker stop lyaim-frontend || true
                  sudo docker rm lyaim-frontend || true
                  sudo docker run -d --name lyaim-frontend -e BASE_URL=${{secrets.BASE_URL}} -p 3000:3000 --restart always narsibhati6545/lyaim-tech-frontend:latest